# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Senior Design App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Senior Design App
  pod 'AWSKinesis'
  pod 'AWSCognitoIdentityProvider'
  pod 'AWSS3', '~> 2.30.0'  # Use the latest version available
  
end
